FBXファイル入れ替えととシェダーファイルの追加
mitunaga870/FPS-Shooting-Game pull request #3
Opened 2024-06-20 08:43 UTC by sirofyu

## タイルマップのFBXファイルをアップデートしました。

- 外側のベベルを削除
- 大きさを統合
- 中心を変更

### **要確認**

- 角タイルの角度について
- デフォルトタイルが見えない

### ShaderファイルにURPシェダーノートファイルを追加しました。
まだBilt In Shaderを使用しているので、UIを整えるときにURPへ変更の予定

2024-06-21 23:54 UTC, mitunaga870 requested changes
- デフォルトタイルのメッシュが登録されていないため、アウトライン周りでエラーを吐くので修正頼む
- デフォルトタイルのメッシュ(Nottingのメッシュ：平面0.006)だけBoundsSizeが0.06*0.06四方になってるけど、できればほかのメッシュと縦横のサイズを一致させてほしい

2024-06-21 23:56 UTC, mitunaga870 commented
- デフォルトタイルはこっちのMesh FIlterに設定して
![image](https://github.com/mitunaga870/FPS-Shooting-Game/assets/94438265/90da8bb0-f5ae-4030-90cd-ce426fee956e)

2024-06-22 02:00 UTC, sirofyu commented
Nothin.fbx(平面006 mesh)のサイズを修正
Tile MeshFilterに平面006を設定
DeafultMeshに平面006を設定

エラー
`Not allowed to access vertices on mesh '平面.006' (isReadable is false; Read/Write must be enabled in import settings) UnityEngine.Mesh:get_vertices () Outline:SmoothNormals (UnityEngine.Mesh) (at Assets/QuickOutline/Scripts/Outline.cs:224) Outline:LoadSmoothNormals () (at Assets/QuickOutline/Scripts/Outline.cs:192) Outline:Awake () (at Assets/QuickOutline/Scripts/Outline.cs:96) UnityEngine.Object:Instantiate<Tile> (Tile,UnityEngine.Vector3,UnityEngine.Quaternion) MazeController:CreateMaze () (at Assets/Scripts/MazeController.cs:94) MazeController:Start () (at Assets/Scripts/MazeController.cs:67)`

について
Nothing.fbxのインスペクター>Read/Writeにチェックを入れると消えたのでご参考までにー　以上ー 

[参考リンク](https://note.com/futinuro/n/ne49e28a1f576)

2024-06-22 02:23 UTC, mitunaga870 requested changes
- gitignoreの件が終わってないのでやっといて
- 素材の角度が変わっちゃってるけど楽に治せそう？治せなそうならコード側で対応する
- コーナーのタイルのマテリアルの設定が逆臭いっす

2024-06-22 02:23 UTC, mitunaga870 commented on .vscode/extensions.json
- gitignoreに以下を追加して.vscode以下のファイルをgit管理外にしといて
  `/.vscode`

2024-06-22 03:10 UTC, sirofyu commented
- .gitignore文末に/.vscodeを追加
- 素材角度を修正（仕様書にXYZの向きまで書いとくべきだった..）
- コーナーのタイルのマテリアルの設定を変更
 ->FBXの仕様書を読み直して、Submeshが逆なのを発見→Blenderでsubmeshを逆転させた

2024-06-22 03:50 UTC, mitunaga870 approved these changes

2024-06-22 03:52 UTC, merged